# -*- coding: utf-8 -*-
"""a7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QEyb5o3L39qqYkGNQMtvcfbYq4YpK_hH
"""

import matplotlib.pyplot as plt 
import numpy as np 


plt.axis([-3,9,-3,12])

plt.axis('on')
plt.grid(True)

A = np.array([2,11])
B = np.array([2,-2])
C = np.array([0,10])
D = np.array([8,0])
E = np.array([-1,3])
F = np.array([8,3])

P = np.array([[-5,-4],
 [1, 0]])
Q = np.array([-40,2]) 
G = np.linalg.solve(P, Q) 

R = np.array([[-5,-4],
 [0, 1]])
S = np.array([-40,3]) 
H = np.linalg.solve(R, S) 

T = np.array([[1,0],
 [0, 1]])
U = np.array([2,3]) 
I = np.linalg.solve(T, U) 

points = np.array((G,H,I))

def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

x_AB = line_gen(A,B)
x_CD = line_gen(C,D)
x_EF = line_gen(E,F)


plt.plot(x_AB[0,:],x_AB[1,:],label='$AB$')
plt.plot(x_CD[0,:],x_CD[1,:],label='$CD$')
plt.plot(x_EF[0,:],x_EF[1,:],label='$EF$')

plt.fill_between(points[:,0], points[:,1])

plt.savefig('inequality.png')

plt.show